#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DPP_DEBUG -DTRACE_SPI_OPS
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = Debug
DEP_DEBUG = 
OUT_DEBUG = Debug/piplates.so

INC_PPTEST_DEBUG = $(INC) -Isrc/api
CFLAGS_PPTEST_DEBUG = $(CFLAGS) -g -DPP_DEBUG -DTRACE_SPI_OPS
RESINC_PPTEST_DEBUG = $(RESINC)
RCFLAGS_PPTEST_DEBUG = $(RCFLAGS)
LIBDIR_PPTEST_DEBUG = $(LIBDIR)
LIB_PPTEST_DEBUG = $(LIB)Debug/libpiplates.so
LDFLAGS_PPTEST_DEBUG = $(LDFLAGS)
OBJDIR_PPTEST_DEBUG = Debug
DEP_PPTEST_DEBUG = 
OUT_PPTEST_DEBUG = Debug/pptest

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = Release
DEP_RELEASE = 
OUT_RELEASE = Release/piplates.so

INC_PPTEST_RELEASE = $(INC) -Isrc/api
CFLAGS_PPTEST_RELEASE = $(CFLAGS) -O2
RESINC_PPTEST_RELEASE = $(RESINC)
RCFLAGS_PPTEST_RELEASE = $(RCFLAGS)
LIBDIR_PPTEST_RELEASE = $(LIBDIR)
LIB_PPTEST_RELEASE = $(LIB)Release/libpiplates.so
LDFLAGS_PPTEST_RELEASE = $(LDFLAGS) -s
OBJDIR_PPTEST_RELEASE = Release
DEP_PPTEST_RELEASE = 
OUT_PPTEST_RELEASE = Release/pptest

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/api/ppapi.o $(OBJDIR_DEBUG)/src/api/spiops.o

OBJ_PPTEST_DEBUG = $(OBJDIR_PPTEST_DEBUG)/src/test/pptest.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/api/ppapi.o $(OBJDIR_RELEASE)/src/api/spiops.o

OBJ_PPTEST_RELEASE = $(OBJDIR_PPTEST_RELEASE)/src/test/pptest.o

all: debug pptest_debug release pptest_release

clean: clean_debug clean_pptest_debug clean_release clean_pptest_release

before_debug: 
	test -d Debug || mkdir -p Debug
	test -d $(OBJDIR_DEBUG)/src/api || mkdir -p $(OBJDIR_DEBUG)/src/api

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) -shared $(LIBDIR_DEBUG) $(OBJ_DEBUG)  -o $(OUT_DEBUG) $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/api/ppapi.o: src/api/ppapi.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/api/ppapi.c -o $(OBJDIR_DEBUG)/src/api/ppapi.o

$(OBJDIR_DEBUG)/src/api/spiops.o: src/api/spiops.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/api/spiops.c -o $(OBJDIR_DEBUG)/src/api/spiops.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf Debug
	rm -rf $(OBJDIR_DEBUG)/src/api

before_pptest_debug: 
	test -d Debug || mkdir -p Debug
	test -d $(OBJDIR_PPTEST_DEBUG)/src/test || mkdir -p $(OBJDIR_PPTEST_DEBUG)/src/test

after_pptest_debug: 

pptest_debug: before_pptest_debug out_pptest_debug after_pptest_debug

out_pptest_debug: before_pptest_debug $(OBJ_PPTEST_DEBUG) $(DEP_PPTEST_DEBUG)
	$(LD) $(LIBDIR_PPTEST_DEBUG) -o $(OUT_PPTEST_DEBUG) $(OBJ_PPTEST_DEBUG)  $(LDFLAGS_PPTEST_DEBUG) $(LIB_PPTEST_DEBUG)

$(OBJDIR_PPTEST_DEBUG)/src/test/pptest.o: src/test/pptest.c
	$(CC) $(CFLAGS_PPTEST_DEBUG) $(INC_PPTEST_DEBUG) -c src/test/pptest.c -o $(OBJDIR_PPTEST_DEBUG)/src/test/pptest.o

clean_pptest_debug: 
	rm -f $(OBJ_PPTEST_DEBUG) $(OUT_PPTEST_DEBUG)
	rm -rf Debug
	rm -rf $(OBJDIR_PPTEST_DEBUG)/src/test

before_release: 
	test -d Release || mkdir -p Release
	test -d $(OBJDIR_RELEASE)/src/api || mkdir -p $(OBJDIR_RELEASE)/src/api

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/api/ppapi.o: src/api/ppapi.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/api/ppapi.c -o $(OBJDIR_RELEASE)/src/api/ppapi.o

$(OBJDIR_RELEASE)/src/api/spiops.o: src/api/spiops.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/api/spiops.c -o $(OBJDIR_RELEASE)/src/api/spiops.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf Release
	rm -rf $(OBJDIR_RELEASE)/src/api

before_pptest_release: 
	test -d Release || mkdir -p Release
	test -d $(OBJDIR_PPTEST_RELEASE)/src/test || mkdir -p $(OBJDIR_PPTEST_RELEASE)/src/test

after_pptest_release: 

pptest_release: before_pptest_release out_pptest_release after_pptest_release

out_pptest_release: before_pptest_release $(OBJ_PPTEST_RELEASE) $(DEP_PPTEST_RELEASE)
	$(LD) $(LIBDIR_PPTEST_RELEASE) -o $(OUT_PPTEST_RELEASE) $(OBJ_PPTEST_RELEASE)  $(LDFLAGS_PPTEST_RELEASE) $(LIB_PPTEST_RELEASE)

$(OBJDIR_PPTEST_RELEASE)/src/test/pptest.o: src/test/pptest.c
	$(CC) $(CFLAGS_PPTEST_RELEASE) $(INC_PPTEST_RELEASE) -c src/test/pptest.c -o $(OBJDIR_PPTEST_RELEASE)/src/test/pptest.o

clean_pptest_release: 
	rm -f $(OBJ_PPTEST_RELEASE) $(OUT_PPTEST_RELEASE)
	rm -rf Release
	rm -rf $(OBJDIR_PPTEST_RELEASE)/src/test

.PHONY: before_debug after_debug clean_debug before_pptest_debug after_pptest_debug clean_pptest_debug before_release after_release clean_release before_pptest_release after_pptest_release clean_pptest_release

